INFO:__main__:Found 2 mismatched records
INFO:__main__:s3 bucket name : s3://app-id-111597-dep-id-114116-uu-id-9x0jt94siuto


ERROR:__main__:Error in sync_dataframe_with_postgresql: An error occurred while calling o457.csv.
: com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: Z51DF8F5T0PRPD9C; S3 Extended Request ID: iTeUgiAo1tLAvKWBm0idw9f5L/s/Go17YBxIMcM7Tva6MzaOo0KcQMclEjNOsyspjPbGmJN+bxk=; Proxy: null), S3 Extended Request ID: iTeUgiAo1tLAvKWBm0idw9f5L/s/Go17YBxIMcM7Tva6MzaOo0KcQMclEjNOsyspjPbGmJN+bxk=
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecuto
